env:
  jest: true
extends: airbnb
parser: "babel-eslint"
plugins:
  - react
  - jsx-a11y
  - import
rules:
  react/jsx-filename-extension:
    - 2
    - extensions:
      - .js
      - .jsx
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - "**/__tests__/**"
